"""
reference_case.py — the real discovery call, end to end.

`intake_priya_raman.txt` is the reference example the mentor named twice: "every
hard problem in this project is sitting in it in plain language." Until now the
intake layer had only ever been tested on synthetic transcripts generated by
this repo's own templating — uniform speaker turns, fixed phrasings, facts
planted at chosen salience. The 98.6% structured accuracy was measured entirely
on that corpus, which is a real limit on what the number means.

This module runs the actual call through the whole path — extract, classify,
bridge, profile — and answers the transcript's own closing line:

    "TODO: build her profile, run the human-capital decomposition, and SHOW her
     how much biotech risk she's carrying before she even opens a brokerage
     account."

What the real transcript broke
------------------------------
It is advisor prose notes, not a dialogue. There are no `CLIENT:` lines, so the
rule-based extractor — which read only those — returned **0 of 12 fields** with
no error at all. That is the failure mode this repo keeps finding: something
that works on the data it was built for, returns empty on the data it was built
*for*, and says nothing. `_client_voice` / `_advisor_voice` in intake.py now
handle both formats, and attribution in prose notes is decided per fact rather
than per line.

It also produced `RSU_concentration = 360000` — the dollar figure, for a field
the contract bounds to [0, 1]. The prompt never stated the unit. `FIELD_UNITS`
now does.

Neither bug was visible on the synthetic corpus.
"""

from __future__ import annotations

from pathlib import Path

from contracts import PipelineDestination, StatementKind
from agents.profile.intake import RuleBasedExtractor, StructuredExtractor
from agents.profile.intake_bridge import build_profile_from_intake

_THIS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = _THIS_DIR.parent.parent
TRANSCRIPT = PROJECT_ROOT / "intake_priya_raman.txt"

CLIENT_ID = "priya_raman"


def load_transcript(path: Path | None = None) -> str:
    path = path or TRANSCRIPT
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. This is the mentor's reference discovery call; "
            "the module has nothing to run without it."
        )
    return path.read_text()


def run(discount_rate: float = 0.0418, extractor=None, save: bool = False):
    """
    Full path on the real call, with the fiduciary summary the transcript asks for.

    Defaults to StructuredExtractor, which needs an API key — the rule-based
    floor cannot classify statements, and on this transcript recovers almost
    nothing, which is itself reported below.
    """
    transcript = load_transcript()
    extractor = extractor or StructuredExtractor()

    # The floor, for contrast. Cheap, offline, and the point of the comparison.
    floor = RuleBasedExtractor().extract(transcript, CLIENT_ID, "priya_raman")
    floor_got = sum(1 for f in floor.fields.values() if f.value is not None)

    extracted = extractor.extract(transcript, CLIENT_ID, "priya_raman")
    got = sum(1 for f in extracted.fields.values() if f.value is not None)

    result = build_profile_from_intake(extracted, discount_rate)

    print("\n=== Reference discovery call — Priya Raman ===")
    print(f"Format: advisor prose notes, no speaker turns, {len(transcript.splitlines())} lines\n")
    print(f"  rule-based floor : {floor_got} of {len(floor.fields)} fields recovered")
    print(f"  {extractor.name:16s} : {got} of {len(extracted.fields)} fields recovered, "
          f"{len(extracted.statements)} statements classified")

    if not result.built:
        print("\n  Profile NOT built — missing required fields:")
        for q in result.open_questions:
            print(f"    ASK: {q}")
        return result

    p = result.profile
    print("\n--- Human-capital decomposition ---")
    print(f"  human capital (PV of earnings)  {p.human_capital_valuation:>14,.0f}")
    print(f"  financial capital               {p.financial_capital:>14,.0f}")
    print(f"  human capital as % of total     {p.human_capital_pct_of_total:>13.1f}%")
    print(f"  income beta to equities         {p.income_equity_beta:>14.3f}   ({p.human_capital_type.value})")
    print(f"  implicit equity exposure        {p.implicit_equity_exposure:>14.3f}")
    print(f"  portfolio equity target         {(p.portfolio_equity_target or 0):>14.3f}   (total-wealth units)")

    # The transcript's actual ask: show her the biotech risk, with her own words.
    print("\n--- What she is already carrying, in her own words ---")
    risk_facts = extracted.statements_of(StatementKind.RISK_FACT)
    for s in risk_facts:
        dests = ", ".join(d.value for d in s.destinations)
        print(f"\n  “{s.quote.strip()[:100]}”")
        print(f"    → {s.summary}")
        print(f"    → routes to: {dests}")

    if (p.portfolio_equity_target or 0) <= 0:
        print(
            f"\n  Her career alone carries implicit equity exposure of "
            f"{p.implicit_equity_exposure:.2f} against a risk budget of "
            f"{p.effective_risk_budget:.2f}. The residual capacity for portfolio "
            f"equity is {p.portfolio_equity_target:.2f} — negative. Before she opens "
            f"a brokerage account she is already over-exposed to equities, and the "
            f"$360k of ARVX sits on top of that."
        )

    print("\n--- Statements needing a human ---")
    for s in extracted.statements_of(StatementKind.CHALLENGE):
        print(f"  {s.summary}")
        print(f"    evidence: “{s.quote.strip()[:90]}”")

    print("\n--- Scope boundaries recorded ---")
    for s in extracted.statements_for(PipelineDestination.SCOPE_BOUNDARY):
        print(f"  {s.summary}")

    if result.conflicts:
        print("\n--- Source conflicts ---")
        for c in result.conflicts:
            print(f"  {c}")

    print(f"\n  stated: {len(result.stated_fields)}   "
          f"defaulted: {len(result.defaulted_fields)} {result.defaulted_fields}")

    if save:
        out = PROJECT_ROOT / "data" / "outputs" / "reference_case_priya.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(extracted.model_dump_json(indent=2))
        print(f"\nSaved → {out}")

    return result


if __name__ == "__main__":  # pragma: no cover
    run(save=True)
